format:
  line_width: 120
  tab_size: 4
  # If true, separate flow control names from their parentheses with a space
  separate_ctrl_name_with_space: true
  max_lines_hwrap: 0
  line_ending: auto
  autosort: true
