repos:
  - repo: https://github.com/doublify/pre-commit-clang-format.git
    rev: 62302476d0da01515660132d76902359bed0f782 # from 08.05.2020
    hooks:
      - id: clang-format
        files: \.(c|cc|cxx|cpp|frag|geom|glsl|h|hpp|vert)$
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: 'e2c2116d86a80e72e7146a06e68b7c228afc6319' # v0.6.13
    hooks:
      - id: cmake-format
        additional_dependencies: ['pyyaml']
      #- id: cmake-lint